import asyncio
from datetime import datetime
from pathlib import Path
from uuid import uuid4

import discord

from ..tools.message_formatting import MessageFormatting

MAX_TTS_TEXT_LENGTH = 5_000

MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10 MB


def register(bot, transcript_service, elevenlabs_service, data_dir, guild_ids):
    voice = bot.create_group(
        "voice_assistant",
        "Voice assistant commands, these can ONLY be used in a voice channel",
        guild_ids=guild_ids,
    )

    @voice.command(name="join", description="Join a voice channel")
    async def join(ctx: discord.ApplicationContext):
        await ctx.defer()
        if ctx.author.voice:
            await ctx.author.voice.channel.connect()
            await MessageFormatting.send_followup(ctx, "Joined the voice channel.")
        else:
            await MessageFormatting.send_followup(
                ctx, "You are not in a voice channel."
            )

    @voice.command(name="leave", description="Leave the voice channel")
    async def leave(ctx: discord.ApplicationContext):
        if ctx.voice_client:
            await ctx.voice_client.disconnect()
            await MessageFormatting.send_response(ctx, "Left the voice channel.")
        else:
            await MessageFormatting.send_response(ctx, "I am not in a voice channel.")

    @voice.command(
        name="list_transcripts", description="List the transcripts generated by OpenAI"
    )
    async def list_transcripts(ctx: discord.ApplicationContext):
        transcripts_dir = _user_transcripts_dir(data_dir, ctx)
        files = sorted(
            transcripts_dir.glob("*.txt"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not files:
            await MessageFormatting.send_response(
                ctx, "No transcripts have been generated yet."
            )
            return
        message = "OpenAI-generated transcripts:\n" + "\n".join(
            f"• {p.name}" for p in files
        )
        await MessageFormatting.send_response(ctx, message)

    @voice.command(
        name="get_transcript", description="Send a saved transcript to you as a file"
    )
    async def get_transcript(ctx: discord.ApplicationContext, name: str):
        path = _transcript_path(_user_transcripts_dir(data_dir, ctx), name)
        if path is None or not path.is_file():
            await MessageFormatting.send_response(
                ctx, f"I couldn't find the transcript `{Path(name).stem}.txt`."
            )
            return
        await ctx.defer()
        try:
            await MessageFormatting.send_direct_message(
                ctx.author,
                f"Here is the transcript `{path.name}`.",
                file=discord.File(str(path)),
            )
            await MessageFormatting.send_followup(
                ctx, "I sent the transcript to your direct messages."
            )
        except discord.Forbidden:
            await MessageFormatting.send_followup(
                ctx,
                "I couldn't send you a direct message. "
                "Please enable DMs from server members.",
            )

    @voice.command(
        name="upload_mp3", description="Upload an MP3 file to the voice assistant"
    )
    async def upload_mp3(ctx: discord.ApplicationContext, file: discord.Attachment):
        if not file.filename.lower().endswith(".mp3"):
            await MessageFormatting.send_response(
                ctx, "Please upload a valid MP3 file."
            )
            return
        user_dir = _user_data_dir(data_dir, ctx)
        recordings_dir = user_dir / "recordings"
        transcripts_dir = user_dir / "transcripts"
        recordings_dir.mkdir(parents=True, exist_ok=True)
        transcripts_dir.mkdir(parents=True, exist_ok=True)
        audio_path = recordings_dir / f"upload_{uuid4().hex}.mp3"
        transcript_path = transcripts_dir / f"transcript_{uuid4().hex}.txt"

        size_bytes = file.size
        if size_bytes > MAX_UPLOAD_SIZE:  # 10 MB limit
            await MessageFormatting.send_response(
                ctx, "The uploaded file exceeds the 10 MB size limit."
            )
            return

        await MessageFormatting.send_response(
            ctx, "File received. Uploading and creating transcript..."
        )
        try:
            with audio_path.open("wb") as output:
                await file.save(output)
            transcript = await transcript_service.create_transcript(str(audio_path))
            transcript_path.write_text(transcript, encoding="utf-8")
            await MessageFormatting.send_followup(ctx, "Transcript created and saved.")
        except Exception as error:
            print(f"MP3 upload/transcription failed: {error}")
            await MessageFormatting.send_followup(
                ctx,
                "I could not create the transcript. Check the bot logs for details.",
            )

    @voice.command(
        name="play_transcript",
        description="Read a saved transcript aloud in your voice channel",
    )
    async def play_transcript(ctx: discord.ApplicationContext, name: str):
        if ctx.author.voice is None or ctx.author.voice.channel is None:
            await MessageFormatting.send_response(
                ctx, "You must be in a voice channel first."
            )
            return
        path = _transcript_path(_user_transcripts_dir(data_dir, ctx), name)
        if path is None or not path.is_file():
            await MessageFormatting.send_response(
                ctx, f"I couldn't find the transcript `{Path(name).stem}.txt`."
            )
            return
        await ctx.defer()
        try:
            text = await asyncio.to_thread(path.read_text, encoding="utf-8")
            audio = await asyncio.to_thread(
                elevenlabs_service.convert_text_to_speech, text
            )
            audio_path = await asyncio.to_thread(
                elevenlabs_service.save_audio,
                audio,
                _user_data_dir(data_dir, ctx)
                / "speech"
                / f"{path.stem}_{datetime.now():%Y%m%d_%H%M%S}.mp3",
            )
            client = ctx.voice_client
            channel = ctx.author.voice.channel
            if client is None:
                client = await channel.connect()
            elif client.channel != channel:
                await client.move_to(channel)
            if client.is_playing():
                client.stop()
            client.play(discord.FFmpegPCMAudio(str(audio_path)))
            await MessageFormatting.send_followup(
                ctx, f"Playing transcript `{path.name}`."
            )
        except Exception as error:
            print(f"Transcript playback failed: {error}")
            await MessageFormatting.send_followup(
                ctx,
                "I could not create or play the transcript audio. Check the bot logs.",
            )

    @voice.command(
        name="eleven_labs",
        description="Convert text to speech and play it in your voice channel",
    )
    async def eleven_labs(ctx: discord.ApplicationContext, text: str):
        if ctx.author.voice is None or ctx.author.voice.channel is None:
            await MessageFormatting.send_response(
                ctx, "You must be in a voice channel first."
            )
            return
        if len(text) > MAX_TTS_TEXT_LENGTH:
            await MessageFormatting.send_response(
                ctx,
                f"The text cannot exceed {MAX_TTS_TEXT_LENGTH:,} characters.",
            )
            return
        await MessageFormatting.send_response(
            ctx, "Creating speech and preparing the voice channel..."
        )
        try:
            audio = await asyncio.to_thread(
                elevenlabs_service.convert_text_to_speech, text
            )
            audio_path = await asyncio.to_thread(
                elevenlabs_service.save_audio,
                audio,
                _user_data_dir(data_dir, ctx)
                / "speech"
                / f"{datetime.now():%Y%m%d_%H%M%S_%f}_{uuid4().hex}.mp3",
            )
            client = ctx.voice_client or await ctx.author.voice.channel.connect()
            if client.is_playing():
                client.stop()
            client.play(discord.FFmpegPCMAudio(str(audio_path)))
            await MessageFormatting.send_followup(
                ctx, "Playing the ElevenLabs speech now."
            )
        except Exception as error:
            print(f"ElevenLabs voice command failed: {error}")
            await MessageFormatting.send_followup(
                ctx,
                "I could not generate or play the speech. "
                "Check the bot logs for details.",
            )


def _user_data_dir(data_dir, ctx) -> Path:
    if ctx.guild is None:
        raise ValueError("This command must be used in a guild.")
    directory = (
        Path(data_dir) / "guilds" / str(ctx.guild.id) / "users" / str(ctx.author.id)
    )
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _user_transcripts_dir(data_dir, ctx) -> Path:
    directory = _user_data_dir(data_dir, ctx) / "transcripts"
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _transcript_path(directory: Path, name: str):
    safe_name = Path(name).name
    if safe_name in {"", ".", ".."}:
        return None
    path = Path(directory) / safe_name
    return path if path.suffix.lower() == ".txt" else path.with_suffix(".txt")
