import asyncio
import logging
from datetime import datetime
from pathlib import Path
from uuid import uuid4

import discord

from bot.errors import AccessDenied, ApplicationError
from bot.modules.client.elevenlabs.elevenlabs import ElevenLabsClient
from bot.modules.client.openai.tool_calls.transcript import Transcript
from bot.settings.settings import Settings

from ..tools.message_formatting import MessageFormatting


def _upload_size_error(size_bytes: int, settings: Settings) -> str | None:
    if size_bytes <= settings.upload_max_bytes:
        return None
    size_limit_mb = settings.upload_max_bytes / (1024 * 1024)
    return (
        "The uploaded file exceeds the configured size limit of "
        f"{size_limit_mb:g} MB."
    )


def _tts_text_error(text: str, settings: Settings) -> str | None:
    if len(text) <= settings.tts_max_characters:
        return None
    return f"The text cannot exceed {settings.tts_max_characters:,} characters."


def register(
    bot: discord.Bot,
    transcript_service: Transcript,
    elevenlabs_service: ElevenLabsClient,
    settings: Settings,
) -> None:
    voice = bot.create_group(
        "voice_assistant",
        "Voice assistant commands, these can ONLY be used in a voice channel",
        guild_ids=list(settings.guild_ids),
    )

    @voice.command(name="join", description="Join a voice channel")
    async def join(ctx: discord.ApplicationContext) -> None:
        await ctx.defer()
        if (
            isinstance(ctx.author, discord.Member)
            and ctx.author.voice
            and ctx.author.voice.channel
        ):
            await ctx.author.voice.channel.connect()
            await MessageFormatting.send_followup(ctx, "Joined the voice channel.")
        else:
            await MessageFormatting.send_followup(
                ctx, "You are not in a voice channel."
            )

    @voice.command(name="leave", description="Leave the voice channel")
    async def leave(ctx: discord.ApplicationContext) -> None:
        if ctx.voice_client:
            await ctx.voice_client.disconnect()
            await MessageFormatting.send_response(ctx, "Left the voice channel.")
        else:
            await MessageFormatting.send_response(ctx, "I am not in a voice channel.")

    @voice.command(
        name="list_transcripts", description="List the transcripts generated by OpenAI"
    )
    async def list_transcripts(ctx: discord.ApplicationContext) -> None:
        transcripts_dir = _user_transcripts_dir(settings.data_dir, ctx)
        files = sorted(
            transcripts_dir.glob("*.txt"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not files:
            await MessageFormatting.send_response(
                ctx, "No transcripts have been generated yet."
            )
            return
        message = "OpenAI-generated transcripts:\n" + "\n".join(
            f"• {p.name}" for p in files
        )
        await MessageFormatting.send_response(
            ctx, message, allowed_mentions=discord.AllowedMentions.none()
        )

    @voice.command(
        name="get_transcript", description="Send a saved transcript to you as a file"
    )
    async def get_transcript(ctx: discord.ApplicationContext, name: str) -> None:
        path = _transcript_path(_user_transcripts_dir(settings.data_dir, ctx), name)
        if path is None or not path.is_file():
            await MessageFormatting.send_response(
                ctx,
                f"I couldn't find the transcript `{Path(name).stem}.txt`.",
                allowed_mentions=discord.AllowedMentions.none(),
            )
            return
        await ctx.defer()
        try:
            await MessageFormatting.send_direct_message(
                ctx.author,
                f"Here is the transcript `{path.name}`.",
                file=discord.File(str(path)),
                allowed_mentions=discord.AllowedMentions.none(),
            )
            await MessageFormatting.send_followup(
                ctx,
                "I sent the transcript to your direct messages.",
                allowed_mentions=discord.AllowedMentions.none(),
            )
        except discord.Forbidden:
            await MessageFormatting.send_followup(
                ctx,
                "I couldn't send you a direct message. "
                "Please enable DMs from server members.",
                allowed_mentions=discord.AllowedMentions.none(),
            )

    @voice.command(
        name="upload_mp3", description="Upload an MP3 file to the voice assistant"
    )
    async def upload_mp3(
        ctx: discord.ApplicationContext, file: discord.Attachment
    ) -> None:
        if not file.filename.lower().endswith(".mp3"):
            await MessageFormatting.send_response(
                ctx, "Please upload a valid MP3 file."
            )
            return
        user_dir = _user_data_dir(settings.data_dir, ctx)
        recordings_dir = user_dir / "recordings"
        transcripts_dir = user_dir / "transcripts"
        recordings_dir.mkdir(parents=True, exist_ok=True)
        transcripts_dir.mkdir(parents=True, exist_ok=True)
        audio_path = recordings_dir / f"upload_{uuid4().hex}.mp3"
        transcript_path = transcripts_dir / f"transcript_{uuid4().hex}.txt"

        size_error = _upload_size_error(file.size, settings)
        if size_error:
            await MessageFormatting.send_response(ctx, size_error)
            return

        await MessageFormatting.send_response(
            ctx, "File received. Uploading and creating transcript..."
        )
        try:
            with audio_path.open("wb") as output:
                await file.save(output)
            transcript = await transcript_service.create_transcript(str(audio_path))
            transcript_path.write_text(transcript, encoding="utf-8")
            await MessageFormatting.send_followup(ctx, "Transcript created and saved.")
        except ApplicationError:
            raise
        except Exception as error:
            logging.getLogger(__name__).error(
                "MP3 upload/transcription failed (%s)", type(error).__name__
            )
            await MessageFormatting.send_followup(
                ctx,
                "I could not create the transcript. Check the bot logs for details.",
            )

    @voice.command(
        name="play_transcript",
        description="Read a saved transcript aloud in your voice channel",
    )
    async def play_transcript(ctx: discord.ApplicationContext, name: str) -> None:
        if not settings.elevenlabs_api_key:
            await MessageFormatting.send_response(
                ctx,
                "ElevenLabs speech is unavailable because ELEVENLABS_API_KEY "
                "is not configured.",
            )
            return
        if (
            not isinstance(ctx.author, discord.Member)
            or ctx.author.voice is None
            or ctx.author.voice.channel is None
        ):
            await MessageFormatting.send_response(
                ctx, "You must be in a voice channel first."
            )
            return
        path = _transcript_path(_user_transcripts_dir(settings.data_dir, ctx), name)
        if path is None or not path.is_file():
            await MessageFormatting.send_response(
                ctx,
                f"I couldn't find the transcript `{Path(name).stem}.txt`.",
                allowed_mentions=discord.AllowedMentions.none(),
            )
            return
        await ctx.defer()
        try:
            text = await asyncio.to_thread(path.read_text, encoding="utf-8")
            audio = await asyncio.to_thread(
                elevenlabs_service.convert_text_to_speech, text
            )
            audio_path = await asyncio.to_thread(
                elevenlabs_service.save_audio,
                audio,
                _user_data_dir(settings.data_dir, ctx)
                / "speech"
                / f"{path.stem}_{datetime.now():%Y%m%d_%H%M%S}.mp3",
            )
            client = ctx.voice_client
            channel = ctx.author.voice.channel
            if client is None:
                client = await channel.connect()
            elif client.channel != channel:
                await client.move_to(channel)
            if client.is_playing():
                client.stop()
            client.play(discord.FFmpegPCMAudio(str(audio_path)))
            await MessageFormatting.send_followup(
                ctx,
                f"Playing transcript `{path.name}`.",
                allowed_mentions=discord.AllowedMentions.none(),
            )
        except ApplicationError:
            raise
        except Exception as error:
            logging.getLogger(__name__).error(
                "Transcript playback failed (%s)", type(error).__name__
            )
            await MessageFormatting.send_followup(
                ctx,
                "I could not create or play the transcript audio. Check the bot logs.",
            )

    @voice.command(
        name="eleven_labs",
        description="Convert text to speech and play it in your voice channel",
    )
    async def eleven_labs(ctx: discord.ApplicationContext, text: str) -> None:
        if not settings.elevenlabs_api_key:
            await MessageFormatting.send_response(
                ctx,
                "ElevenLabs speech is unavailable because ELEVENLABS_API_KEY "
                "is not configured.",
            )
            return
        if (
            not isinstance(ctx.author, discord.Member)
            or ctx.author.voice is None
            or ctx.author.voice.channel is None
        ):
            await MessageFormatting.send_response(
                ctx, "You must be in a voice channel first."
            )
            return
        text_error = _tts_text_error(text, settings)
        if text_error:
            await MessageFormatting.send_response(ctx, text_error)
            return
        await MessageFormatting.send_response(
            ctx, "Creating speech and preparing the voice channel..."
        )
        try:
            audio = await asyncio.to_thread(
                elevenlabs_service.convert_text_to_speech, text
            )
            audio_path = await asyncio.to_thread(
                elevenlabs_service.save_audio,
                audio,
                _user_data_dir(settings.data_dir, ctx)
                / "speech"
                / f"{datetime.now():%Y%m%d_%H%M%S_%f}_{uuid4().hex}.mp3",
            )
            client = ctx.voice_client or await ctx.author.voice.channel.connect()
            if client.is_playing():
                client.stop()
            client.play(discord.FFmpegPCMAudio(str(audio_path)))
            await MessageFormatting.send_followup(
                ctx, "Playing the ElevenLabs speech now."
            )
        except ApplicationError:
            raise
        except Exception as error:
            logging.getLogger(__name__).error(
                "ElevenLabs voice command failed (%s)", type(error).__name__
            )
            await MessageFormatting.send_followup(
                ctx,
                "I could not generate or play the speech. "
                "Check the bot logs for details.",
            )


def _user_data_dir(data_dir: Path, ctx: discord.ApplicationContext) -> Path:
    if ctx.guild is None:
        raise AccessDenied("This command must be used in a guild.")
    directory = (
        data_dir.resolve() / "guilds" / str(ctx.guild.id) / "users" / str(ctx.author.id)
    )
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _user_transcripts_dir(data_dir: Path, ctx: discord.ApplicationContext) -> Path:
    directory = _user_data_dir(data_dir, ctx) / "transcripts"
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def _transcript_path(directory: Path, name: str) -> Path | None:
    safe_name = Path(name).name
    if safe_name in {"", ".", ".."}:
        return None
    path = Path(directory) / safe_name
    return path if path.suffix.lower() == ".txt" else path.with_suffix(".txt")
